// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAUscFxu-Cmd2laENEsv8bm9uWqmU4LCg',
    appId: '1:1037018857922:web:a9fb4d884caa6ffe4d165b',
    messagingSenderId: '1037018857922',
    projectId: 'to-do-app-2157d',
    authDomain: 'to-do-app-2157d.firebaseapp.com',
    storageBucket: 'to-do-app-2157d.firebasestorage.app',
    measurementId: 'G-MFRTPKD561',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFGrYkd7OwCl2L64PxO57Ll8jn7-M218',
    appId: '1:1037018857922:android:b61771a8088c0bb74d165b',
    messagingSenderId: '1037018857922',
    projectId: 'to-do-app-2157d',
    storageBucket: 'to-do-app-2157d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5GsUfGO2CAfV4RO0sUmjiTPHUd0IXZR8',
    appId: '1:1037018857922:ios:057fbb811a1e32bc4d165b',
    messagingSenderId: '1037018857922',
    projectId: 'to-do-app-2157d',
    storageBucket: 'to-do-app-2157d.firebasestorage.app',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5GsUfGO2CAfV4RO0sUmjiTPHUd0IXZR8',
    appId: '1:1037018857922:ios:057fbb811a1e32bc4d165b',
    messagingSenderId: '1037018857922',
    projectId: 'to-do-app-2157d',
    storageBucket: 'to-do-app-2157d.firebasestorage.app',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAUscFxu-Cmd2laENEsv8bm9uWqmU4LCg',
    appId: '1:1037018857922:web:ee735d4d28ed074c4d165b',
    messagingSenderId: '1037018857922',
    projectId: 'to-do-app-2157d',
    authDomain: 'to-do-app-2157d.firebaseapp.com',
    storageBucket: 'to-do-app-2157d.firebasestorage.app',
    measurementId: 'G-R2Q9CN8884',
  );
}
